### PR TITLE
Added DAPHNE-related data types to the readout_type_scan integtest

### PR DESCRIPTION
**Pull request by bieryAtFnal**

### CODE REVIEW

**Comment by bieryAtFnal** [comment]
To test this change, I have been including the following repo/branch combinations in my software area:

- daqdataformats wketchum/add_daphne_stream_type
- daq-systemtest kbiery/readout_type_scan_with_daphne
- fdreadoutlibs wketchum/add_daphne_stream_type
- fdreadoutmodules kbiery/fakecardreader_pdsstream
- hdf5libs develop
- readoutlibs develop
- readoutmodules develop

The related PRs are the following:

- [daqdataformats 46](https://github.com/DUNE-DAQ/daqdataformats/pull/46)
- [fdreadoutlibs 129](https://github.com/DUNE-DAQ/fdreadoutlibs/pull/129)
- [fdreadoutmodules 7](https://github.com/DUNE-DAQ/fdreadoutmodules/pull/7)

**Comment by bieryAtFnal** [comment]
An updated set of instructions for testing this PR, as of 08:15 CDT on 03-Aug...

I start with the instructions for a v4.1.0 software area [here](https://github.com/DUNE-DAQ/daqconf/wiki/Instructions-for-setting-up-an-fddaq%E2%80%90v4.1.0-software-area).

Then I add and/or update to the following branches/tags in the specified repositories: 

- daqdataformats patch/v4.1.x
- fdreadoutlibs patch/v4.1.x
- fdreadoutmodules patch/v4.1.x
- readoutlibs patch/v4.1.x
- hdf5libs fddaq-v4.1.0
- readoutmodules fddaq-v4.1.0
- daq-systemtest kbiery/readout_type_scan_with_daphne

To test this change, I build the software area, then
- `cd sourcecode/daq-systemtest/integtest`
- `pytest -s readout_type_scan.py --nanorc-option partition-number 2`

If all 18 tests within the readout_type_scan are successful (especially the six new PDS/DAPHNE ones), then the changes in this PR are working correctly.

**Comment by wesketchum** [comment]
@bieryAtFnal @ron003 one minor addendum: would recommend using the fddaq-v4.1.0 tag for hdf5libs and readoutmodules above, not develop. Just for safety (though I expect develop would still be ok).

**Comment by bieryAtFnal** [comment]
Ah, of course, good catch, thanks.
Will fix...

**Comment by ron003** [comment]
I followed the instructions and ran the test 4 times and each time I got "18 passed".
I ran the tests on iceberg03.
Does that seem good?

**Comment by ron003** [comment]
Should I (if I can) do the review? and approve the PR?

**Comment by bieryAtFnal** [comment]
That success rate sounds great.
Yes, please review/approve.

**Review by ron003 — APPROVED** [review]
ran integ test readout_type_scan.py multiple times

**Pull request merged**
